#!/usr/bin/env python3
"""
generate-video-singleshot.py — single Seedance 2.0 call for full multi-shot video.

Compatible with Python 3.8+ (uses __future__ annotations for newer typing syntax).

Combines all cuts from video-brief.json into ONE multi-shot prompt and submits
to FAL Seedance 2.0 reference-to-video (or image-to-video) endpoint with one
reference image (product hero by default).

Use this when you want a single continuous video generated by Seedance from a
multi-shot description, rather than per-cut clips composed in ffmpeg.

Usage:
    python3 generate-video-singleshot.py \\
        --brief /documents/ads/video/[slug]/video-brief.json \\
        --output /documents/ads/video/[slug]/final-singleshot.mp4 \\
        --mode reference-to-video \\
        --tier standard

Endpoints:
    reference-to-video — reference photo as style/identity anchor (default)
    image-to-video      — reference photo as actual starting frame
"""
from __future__ import annotations
import argparse
import asyncio
import base64
import json
import os
import sys
import tempfile
import time
from pathlib import Path
from typing import List, Optional

from runtime_env import ensure_env_var

ENDPOINTS = {
    ("reference-to-video", "standard"): "bytedance/seedance-2.0/reference-to-video",
    ("reference-to-video", "fast"): "bytedance/seedance-2.0/fast/reference-to-video",
    ("image-to-video", "standard"): "bytedance/seedance-2.0/image-to-video",
    ("image-to-video", "fast"): "bytedance/seedance-2.0/fast/image-to-video",
}


def encode_data_url(path: Path) -> str:
    """Fallback: data URL encoding (works for fal-ai/openai/* image models, NOT Seedance)."""
    suffix = path.suffix.lower().lstrip(".")
    mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "webp": "image/webp"}.get(suffix, "image/jpeg")
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")
    return f"data:{mime};base64,{encoded}"


def probe_duration(video_path: Path) -> Optional[float]:
    """Return the duration of a video file in seconds via ffprobe, or None on error."""
    import shutil
    import subprocess

    if not shutil.which("ffprobe"):
        return None
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", str(video_path)],
            capture_output=True, text=True, timeout=20,
        )
        return float(result.stdout.strip()) if result.returncode == 0 else None
    except Exception:
        return None


def probe_has_audio(video_path: Path) -> bool:
    """Return True if the video file has at least one audio stream."""
    import shutil
    import subprocess

    if not shutil.which("ffprobe"):
        return True  # Assume yes; ffmpeg will surface the error if not.
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "a", "-show_entries",
             "stream=codec_type", "-of", "default=noprint_wrappers=1:nokey=1", str(video_path)],
            capture_output=True, text=True, timeout=20,
        )
        return bool(result.stdout.strip())
    except Exception:
        return True


def mix_voiceover_with_video(video_path: Path, vo_path: Path, output_path: Path,
                             fade_out_s: float = 1.5,
                             vo_volume: float = 2.5,
                             bg_volume: float = 0.8,
                             ducking_threshold: float = 0.05,
                             ducking_ratio: float = 8.0,
                             ducking_attack: int = 20,
                             ducking_release: int = 300,
                             vo_mix_weight: float = 1.6) -> bool:
    """Mix voiceover MP3 into the Seedance video's existing audio (music+SFX)."""
    import shutil
    import subprocess

    if not shutil.which("ffmpeg"):
        print("   ⚠ ffmpeg not found in PATH — install with `brew install ffmpeg`")
        return False

    # Probe duration so we can position the fade at the end
    duration = probe_duration(video_path)
    if duration is None or duration <= 0:
        # Fall back to no fade if probe fails
        afade_out = ""
        vfade_out = ""
    else:
        fade_start = max(0.0, duration - fade_out_s)
        afade_out = f",afade=t=out:st={fade_start:.2f}:d={fade_out_s:.2f}"
        # Video fade — slightly shorter, lands cleanly on the last frame
        vfade_d = max(0.5, fade_out_s - 0.3)
        vfade_start = max(0.0, duration - vfade_d)
        vfade_out = f"fade=t=out:st={vfade_start:.2f}:d={vfade_d:.2f}"

    # Detect whether the input video already has an audio track (Seedance
    # music+SFX). If not, we can't mix — we just attach the voiceover as the
    # sole audio track.
    has_audio = probe_has_audio(video_path)
    # Pad audio to exactly the video duration (apad whole_dur), so VO that's
    # shorter than video doesn't get truncated by amix duration=first.
    pad_dur = f"{duration:.3f}" if duration else "15"
    if has_audio:
        filter_complex = (
            f"[1:a]volume={vo_volume},apad=whole_dur={pad_dur},asplit=2[vo_main][vo_sc];"
            f"[0:a]volume={bg_volume}[bg];"
            f"[bg][vo_sc]sidechaincompress=threshold={ducking_threshold}:ratio={ducking_ratio}:"
            f"attack={ducking_attack}:release={ducking_release}:makeup=1[bgduck];"
            f"[bgduck][vo_main]amix=inputs=2:duration=longest:dropout_transition=0:weights=1 {vo_mix_weight},"
            f"alimiter=limit=0.95{afade_out}[aout]"
        )
        print(f"   → Sidechain ducking: vo×{vo_volume} bg×{bg_volume} ratio={ducking_ratio} thr={ducking_threshold}")
    else:
        # Silent input — VO becomes sole audio. Bump volume since no music to mask it.
        solo_volume = max(vo_volume * 0.72, 1.5)
        filter_complex = (
            f"[1:a]volume={solo_volume},apad=whole_dur={pad_dur},"
            f"alimiter=limit=0.95{afade_out}[aout]"
        )
        print(f"   → Silent input — VO sole track, volume×{solo_volume:.2f}")

    # ffmpeg can't read and write the same file in-place. If source == output,
    # write to a temp path first then move it back.
    same_file = video_path.resolve() == output_path.resolve()
    write_to = output_path.with_name(output_path.stem + ".__mix_tmp__" + output_path.suffix) if same_file else output_path

    cmd = ["ffmpeg", "-y",
           "-i", str(video_path),
           "-i", str(vo_path),
           "-filter_complex", filter_complex,
           "-map", "0:v",
           "-map", "[aout]"]
    # Apply video fade-out — re-encodes video (cannot use -c:v copy with -vf)
    if vfade_out:
        cmd += ["-vf", vfade_out, "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p"]
    else:
        cmd += ["-c:v", "copy"]
    cmd += ["-c:a", "aac", "-b:a", "192k", "-shortest", str(write_to)]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        if result.returncode != 0:
            print(f"   ⚠ ffmpeg returncode {result.returncode}")
            print(f"   stderr (last 500 chars): {result.stderr[-500:]}")
            if write_to != output_path and write_to.exists():
                try:
                    write_to.unlink()
                except Exception:
                    pass
            return False
        # Move temp file over the original if we used a temp path
        if same_file:
            write_to.replace(output_path)
        size_mb = output_path.stat().st_size / (1024 * 1024)
        fade_note = f" (audio+video fade-out {fade_out_s}s)" if afade_out else ""
        # Sanity check — the output MUST have audio. If it doesn't, ffmpeg
        # claimed success but produced a broken file.
        if not probe_has_audio(output_path):
            print(f"   ❌ Output file has NO audio stream! ffmpeg may have lost the VO.")
            print(f"   ffmpeg cmd was: {' '.join(cmd)}")
            print(f"   stderr (last 800 chars): {result.stderr[-800:]}")
            return False
        out_dur = probe_duration(output_path)
        print(f"   ✓ Mixed audio written → {output_path.name} ({size_mb:.1f} MB, duration {out_dur:.1f}s){fade_note}")
        return True
    except Exception as e:
        print(f"   ⚠ ffmpeg mix exception: {e}")
        if write_to != output_path and write_to.exists():
            try:
                write_to.unlink()
            except Exception:
                pass
        return False


def _mix_kwargs_from_args(args_namespace) -> dict:
    """Build the kwargs dict for mix_voiceover_with_video() from CLI args."""
    if args_namespace is None:
        return {"fade_out_s": 1.5}
    return {
        "fade_out_s": getattr(args_namespace, "fade_out", 1.5),
        "vo_volume": getattr(args_namespace, "vo_volume", 2.5),
        "bg_volume": getattr(args_namespace, "bg_volume", 0.8),
        "ducking_threshold": getattr(args_namespace, "ducking_threshold", 0.05),
        "ducking_ratio": getattr(args_namespace, "ducking_ratio", 8.0),
        "ducking_attack": getattr(args_namespace, "ducking_attack", 20),
        "ducking_release": getattr(args_namespace, "ducking_release", 300),
        "vo_mix_weight": getattr(args_namespace, "vo_mix_weight", 1.6),
    }


async def upload_to_fal(path: Path) -> str:
    """Upload a file to FAL storage and return the public CDN URL.

    Required for Seedance video endpoints — they reject data URLs and require
    publicly accessible HTTPS URLs.
    """
    import fal_client
    upload_path = prepare_seedance_reference(path)
    try:
        return await fal_client.upload_file_async(str(upload_path))
    finally:
        if upload_path != path:
            try:
                upload_path.unlink()
            except OSError:
                pass


def prepare_seedance_reference(path: Path, max_bytes: int = 30 * 1024 * 1024, max_long_side: int = 2048) -> Path:
    """Downsize oversized reference images before Seedance upload."""
    try:
        if path.stat().st_size <= max_bytes:
            return path
    except OSError:
        return path

    try:
        from PIL import Image
    except ImportError:
        return path

    with Image.open(path) as image:
        resampling = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
        image.thumbnail((max_long_side, max_long_side), resampling)
        if image.mode not in {"RGB", "L"}:
            image = image.convert("RGB")

        tmp = tempfile.NamedTemporaryFile(
            prefix=f"{path.stem}-seedance-ref-",
            suffix=".jpg",
            delete=False,
        )
        tmp_path = Path(tmp.name)
        tmp.close()
        image.save(tmp_path, format="JPEG", quality=90, optimize=True)

    try:
        if tmp_path.stat().st_size < path.stat().st_size:
            return tmp_path
    except OSError:
        return tmp_path

    try:
        tmp_path.unlink()
    except OSError:
        pass
    return path


def extract_product_anatomy_short(product_visual: str, max_chars: int = 600) -> str:
    """Extract a concise (~80-100 words) anatomy summary from the long product_visual_identity.

    Seedance can't absorb 1000-word identity blocks, but a short anatomy paragraph
    helps it lock onto the silhouette when combined with the reference photos.
    """
    if not product_visual:
        return ""
    # Try to grab the first sentence + the EXACT VISUAL ANATOMY section if present
    # Otherwise just truncate at sentence boundary near max_chars.
    text = product_visual.replace("\n", " ").strip()
    if len(text) <= max_chars:
        return text
    # Truncate at last sentence boundary before max_chars
    truncated = text[:max_chars]
    last_period = truncated.rfind(". ")
    if last_period > max_chars * 0.6:
        return truncated[:last_period + 1]
    return truncated + "..."


def build_combined_prompt(brief: dict, ref_count: int = 4, has_storyboard_first: bool = True, has_voiceover: bool = False) -> str:
    """Build a concise multi-shot prompt for Seedance 2.0 reference-to-video.

    Follows Seedance 2.0 recommended structure: Subject → Action → Environment →
    Camera → Audio. Target length ~300-400 words. Reference legend first, then
    one compact line per shot, then global rules, then audio.
    """
    cuts = brief.get("cuts", [])
    sc = brief.get("shared_choices", {})

    style_phrases = {
        "anamorphic-editorial": "anamorphic 35mm film, low-contrast nostalgic highlights, vintage Polaroid softness",
        "commercial-cinematic": "commercial anamorphic, polished color grade, accurate skin tones",
        "handheld-ugc": "handheld phone-style, natural light, authentic creator aesthetic",
        "minimal-product": "controlled lighting, monochromatic, premium sterile aesthetic",
    }
    style_phrase = style_phrases.get(sc.get("style_preset", "anamorphic-editorial"), style_phrases["anamorphic-editorial"])

    n_cuts = len(cuts)
    storyboard_first = has_storyboard_first
    storyboard_only = storyboard_first and ref_count == 1
    product_ref_count = max(0, ref_count - 1) if storyboard_first else ref_count

    # Per-shot lines — Seedance Subject/Action/Environment/Camera format,
    # ~40-50 words each. The shot.subject_framing is trimmed to first 1-2
    # complete sentences (~150-200 chars), with bracketed prefixes stripped
    # and any unmatched brackets/parens cleaned up.
    import re
    cumulative_t = 0
    shot_lines = []
    for i, cut in enumerate(cuts, 1):
        d = int(cut["duration"])
        t_start = cumulative_t
        t_end = cumulative_t + d
        action = cut.get("subject_framing") or cut.get("video_prompt", "")
        # 1. Strip any leading "[FIXED SCENE: ...]" or similar bracketed prefix.
        action = re.sub(r"^\s*\[[^\]]*\]\s*", "", action).strip()
        # 2. Split into sentences and take the first 1-2 (up to ~200 chars).
        sentences = re.split(r"(?<=[.!?])\s+", action)
        kept = []
        running = 0
        target = 200
        for s in sentences:
            if not s.strip():
                continue
            if running == 0 or running + len(s) <= target:
                kept.append(s.strip())
                running += len(s) + 1
            else:
                break
        action = " ".join(kept).strip()
        # 3. If even the first sentence is huge (>240 chars), hard-cut at
        # last word boundary inside 200 chars and force a period.
        if len(action) > 240:
            space_at = action.rfind(" ", 0, 200)
            if space_at > 80:
                action = action[:space_at].rstrip(",;:- ") + "."
            else:
                action = action[:200].rstrip(",;:- ") + "."
        # 4. Strip any unmatched opening parens/brackets to avoid syntax noise.
        if action.count("(") > action.count(")"):
            # Drop the trailing fragment from the unmatched paren onward.
            last_open = action.rfind("(")
            action = action[:last_open].rstrip(",;:- ") + "."
        if action.count("[") > action.count("]"):
            last_open = action.rfind("[")
            action = action[:last_open].rstrip(",;:- ") + "."
        shot_type = cut.get("shot_type", "WIDE")
        focal = cut.get("focal_length", "50mm")
        cam_move = cut.get("camera_move", "STATIC")
        line = f"Shot {i} ({t_start}-{t_end}s, {shot_type} {focal} {cam_move}): {action}"
        shot_lines.append(line)
        cumulative_t = t_end

    total = cumulative_t
    shots_block = "\n".join(shot_lines)

    # Audio cues split into SFX vs music
    audio_tone_list = sc.get("audio_tone", ["ambient"])
    music_keywords = ("piano", "strings", "guitar", "synth", "music", "melody", "score", "soundtrack", "reverb")
    music_cues = [c for c in audio_tone_list if any(k in c.lower() for k in music_keywords)]
    sfx_cues = [c for c in audio_tone_list if c not in music_cues]
    sfx_str = ", ".join(sfx_cues[:3]) if sfx_cues else "soft ambient"
    music_str = ", ".join(music_cues[:2]) if music_cues else "subtle cinematic underscore"
    mood = ", ".join(sc.get("mood_keywords", ["cinematic"])[:4])

    # Reference legend — compact
    ref_lines = []
    if storyboard_first:
        panel_locator = (
            f"Bottom 2/3 holds {n_cuts} numbered panels in a 3×2 grid (or 6×1 strip for 9:16), "
            f"read left-to-right top-to-bottom. Panel N = exact first frame of Shot N."
        )
        if storyboard_only:
            ref_lines.append(f"@Image1 — master storyboard. Source of composition, character, environment, framing, palette. {panel_locator}")
        else:
            ref_lines.append(
                f"@Image1 — master storyboard. Composition, environment, framing, palette. "
                f"Top-left character sheet shows ONE protagonist from 5 angles (NOT five people). {panel_locator}"
            )
            if product_ref_count > 0:
                last = 1 + product_ref_count
                tag_range = f"@Image2-@Image{last}" if product_ref_count > 1 else "@Image2"
                ref_lines.append(
                    f"{tag_range} — angle variants of the SAME single physical product (identity reference for ONE object). "
                    f"Lock silhouette, branding, colors pixel-precisely. NOT additional copies to render alongside."
                )
    ref_legend = "\n".join(ref_lines)

    # Product fidelity + single-instance clause. The single-instance rule is the
    # mirror of CHARACTER COUNT — without it Seedance treats the product visible
    # in @Image1's panels AND the @Image2-N references as separate objects to
    # render together, producing duplicated/echoed product instances per shot.
    product_fidelity = ""
    if not storyboard_only and product_ref_count > 0:
        product_tags = "/".join(f"@Image{i}" for i in range(2, 2 + product_ref_count))
        product_fidelity = (
            f"PRODUCT: exactly ONE product instance per shot, placed precisely as shown in @Image1's panel — "
            f"never duplicated, mirrored, echoed, inset, or rendered twice within a frame. {product_tags} are "
            f"angle/lighting variants of that SAME single physical object, NOT additional products to add. "
            f"Match silhouette, proportions, branding, colors pixel-precisely. "
        )

    # Character archetype — pull dynamically from brief.character so we don't
    # hardcode "mother in her mid-30s + child" from a single campaign.
    char = brief.get("character") or {}
    char_desc = (char.get("description") or "").strip()
    if char_desc:
        # Trim long descriptions to first 1-2 sentences (~220 chars)
        if len(char_desc) > 220:
            cut_at = char_desc.rfind(". ", 0, 220)
            if cut_at > 80:
                char_desc = char_desc[: cut_at + 1]
            else:
                space_at = char_desc.rfind(" ", 0, 220)
                char_desc = (char_desc[:space_at] if space_at > 80 else char_desc[:220]).rstrip(",;:- ") + "."
        char_archetype_clause = f"Generate a fresh, fictional face that fits the archetype: {char_desc} — invent the face entirely."
        char_count_clause = "the SAME single fictional individual(s) described in each shot, across all shots, never duplicated, mirrored, or echoed within a frame"
    else:
        char_archetype_clause = "Generate a fresh, fictional face for the protagonist that fits the archetype shown in the storyboard's character sheet — invent the face entirely."
        char_count_clause = "the SAME single fictional individual(s) described in each shot, across all shots, never duplicated, mirrored, or echoed within a frame"

    # Voiceover audio clause
    vo_extra = (
        " A pre-rendered voiceover is mixed on top in post — leave mid-range headroom for the spoken voice; do not peak loud where dialog lands. NO dialog/lyrics/voiceover in the generated audio."
        if has_voiceover else
        " NO dialog, NO sung lyrics — purely instrumental BGM."
    )

    prompt = f"""A {total}s cinematic {brief.get('aspect_ratio', '16:9')} ad in {n_cuts} connected shots. Style: {style_phrase}. Mood: {mood}.

CHARACTERS (fictional, not real persons): {char_archetype_clause.replace('Generate a fresh, fictional face that fits the archetype: ', '').replace(' — invent the face entirely.', '')} Treat @Image1's character sheet as loose archetype guidance — do NOT 1:1 copy the face. Internal continuity required: same invented face across all {n_cuts} shots (same hair, age, wardrobe). {char_count_clause.replace('the SAME single fictional individual(s) described in each shot, across all shots, ', 'Exact people per shot, ')}.

References:
{ref_legend}

Shots:
{shots_block}

START FRAME RULE: each shot opens by reproducing its assigned panel from @Image1 — match composition, framing, blocking, product placement, environment, lighting, palette. The first ~0.3s is a near-static match of the panel; only then does the camera animate. {product_fidelity}

FACES: photorealistic, like a real person on 35mm film. Forbidden: plastic/porcelain doll skin, beauty-filter perfection, symmetric features, glassy waxy sheen, uncanny eye whites, fused fingers, stock-photo influencer face, CGI sheen.

Audio (Seedance native): ambient SFX ({sfx_str}) + instrumental music ({music_str}) gradating across the {total}s arc — soft start, gentle swell, natural resolution on a held final note. Never abrupt cuts or mid-phrase fades.{vo_extra}"""

    return prompt


def collect_references(
    brief: dict,
    brief_path: Path,
    max_refs: int = 4,
    include_storyboard: bool = True,
    keyframes_dir: Optional[Path] = None,
) -> list[Path]:
    """Collect up to N reference images for Seedance reference-to-video.

    Default strategy:
    Send the master storyboard as @Image1, then product photos as @Image2+.
    This keeps composition/character/pacing anchored by the storyboard while
    product photos lock the exact product identity without adding extra objects.

    Priority order:
      1. Master storyboard PNG (sibling of brief)
      2-N. Product hero + additional product photos
      Fallback. Optional per-cut keyframes when explicitly provided
    """
    refs: list[Path] = []

    # 1. Master storyboard FIRST (becomes @Image1 — overall composition + character)
    storyboard = brief_path.parent / "01-master-storyboard.png"
    if include_storyboard and storyboard.exists():
        refs.append(storyboard)

    # 2..N. Product photos (becomes @Image2, @Image3, ... — exact product identity lock)
    # These pass content policy (no faces) and pin the product's visual look.
    product = brief.get("product") or {}
    hero = product.get("hero_image")
    if hero and Path(hero).exists() and Path(hero) not in refs and len(refs) < max_refs:
        refs.append(Path(hero))
    for p in (product.get("additional_images") or []):
        if len(refs) >= max_refs:
            break
        rp = Path(p)
        if rp.exists() and rp not in refs:
            refs.append(rp)

    # Optional: per-cut keyframes (only if explicitly given via keyframes_dir AND we
    # still have ref slots). Disabled by default because face-heavy keyframes triggered
    # ByteDance content policy — storyboard + product photos pass cleanly.
    if keyframes_dir and keyframes_dir.exists() and len(refs) < max_refs:
        for cut in brief.get("cuts", []):
            cut_id = cut.get("id", "")
            kf = keyframes_dir / f"{cut_id}-keyframe.png"
            if kf.exists() and len(refs) < max_refs:
                refs.append(kf)

    return refs[:max_refs]


async def generate(brief: dict, brief_path: Path, output: Path, mode: str, tier: str, ref_overrides: Optional[List[Path]] = None, args_namespace=None) -> dict:
    try:
        import fal_client
    except ImportError:
        return {"ok": False, "error": "fal-client not installed in provider image"}
    try:
        import requests
    except ImportError:
        return {"ok": False, "error": "requests not installed in provider image"}

    if not ensure_env_var("FAL_KEY"):
        return {"ok": False, "error": "FAL_KEY is not set in env, ~/.openclaw/.env, or Control Center secret store"}

    endpoint = ENDPOINTS.get((mode, tier))
    if not endpoint:
        return {"ok": False, "error": f"unknown mode/tier combo: {mode}/{tier}"}

    if ref_overrides:
        refs = ref_overrides
    else:
        max_refs = getattr(args_namespace, "max_refs", 4)
        include_storyboard = getattr(args_namespace, "include_storyboard", True)
        kf_dir_arg = getattr(args_namespace, "keyframes_dir", None)
        keyframes_dir = Path(kf_dir_arg) if kf_dir_arg else None
        refs = collect_references(
            brief, brief_path,
            max_refs=max_refs,
            include_storyboard=include_storyboard,
            keyframes_dir=keyframes_dir,
        )
    if not refs:
        return {"ok": False, "error": "no reference images found"}

    # The master storyboard is intentionally the first reference, so it maps to
    # @Image1 in the Seedance prompt. Product photos follow as @Image2+.
    storyboard_path = brief_path.parent / "01-master-storyboard.png"
    has_storyboard_first = bool(refs and refs[0] == storyboard_path)
    voiceover_path = getattr(args_namespace, "voiceover", None) if args_namespace else None
    has_voiceover = bool(voiceover_path and Path(voiceover_path).exists())
    prompt = build_combined_prompt(brief, ref_count=len(refs), has_storyboard_first=has_storyboard_first, has_voiceover=has_voiceover)
    total_duration = sum(int(c["duration"]) for c in brief.get("cuts", []))
    aspect = brief.get("aspect_ratio", "16:9")

    if total_duration > 15:
        print(f"⚠️  Total duration {total_duration}s exceeds Seedance max 15s — clamping to 15s")
        total_duration = 15

    # Upload references to FAL CDN — Seedance video endpoints REJECT data URLs,
    # they only accept publicly accessible HTTPS URLs. Parallelized (asyncio.gather)
    # because uploads are network-bound and order in image_urls maps to @ImageN —
    # gather() preserves input order regardless of completion order.
    print(f"→ Uploading {len(refs)} reference images to FAL CDN (parallel)...")
    upload_results = await asyncio.gather(
        *[upload_to_fal(r) for r in refs], return_exceptions=True
    )
    uploaded_urls = []
    for r, res in zip(refs, upload_results):
        if isinstance(res, Exception):
            print(f"     ✗ {r.name} upload failed: {res}")
            return {"ok": False, "error": f"upload failed for {r.name}: {res}"}
        uploaded_urls.append(res)
        print(f"     ✓ {r.name} → {res[:80]}...")

    resolution = getattr(args_namespace, "resolution", "480p") if args_namespace else "480p"
    arguments = {
        "prompt": prompt,
        "duration": str(total_duration),
        "aspect_ratio": aspect,
        "resolution": resolution,
        "generate_audio": brief.get("audio", {}).get("preset") != "silent",
    }

    if mode == "image-to-video":
        # image-to-video uses single starting frame — use the first uploaded ref
        arguments["image_url"] = uploaded_urls[0]
    elif mode == "reference-to-video":
        # reference-to-video accepts a list — index in array maps to @ImageN tag
        # (1st url = @Image1, 2nd = @Image2, etc.). The correct FAL param name is
        # `image_urls`, NOT `reference_image_urls`.
        arguments["image_urls"] = uploaded_urls

    # Voiceover handling — Seedance reference-to-video doesn't accept arbitrary
    # narration audio as output (audio_urls is undocumented for this endpoint and
    # gives a silent video). Strategy: let Seedance generate native music+SFX,
    # then ffmpeg-mix the voiceover on top with sidechain ducking after the
    # video is downloaded.
    voiceover_path = getattr(args_namespace, "voiceover", None) if args_namespace else None
    if voiceover_path and Path(voiceover_path).exists():
        print(f"→ Voiceover detected: {voiceover_path}")
        print(f"   Strategy: Seedance generates music+SFX → ffmpeg mix VO on top with ducking")

    print()
    print(f"→ Endpoint: {endpoint}")
    print(f"→ Duration: {total_duration}s, Aspect: {aspect}, Resolution: {resolution}")
    print(f"→ Prompt: {len(prompt)} chars / {len(prompt.split())} words")
    print(f"→ Refs (uploaded HTTPS URLs): {len(uploaded_urls)}")
    print()
    print("--- PROMPT ---")
    print(prompt)
    print("--- END PROMPT ---")
    print()

    # Dry run — print everything we would submit without paying for FAL.
    if getattr(args_namespace, "dry_run", False):
        print("🟡 --dry-run — skipping FAL submit. Refs uploaded for inspection but no video generated.")
        return {
            "ok": True,
            "dry_run": True,
            "endpoint": endpoint,
            "uploaded_urls": uploaded_urls,
            "prompt_length_chars": len(prompt),
            "prompt_word_count": len(prompt.split()),
            "duration_s": total_duration,
            "aspect": aspect,
            "resolution": resolution,
        }

    start = time.time()
    content_policy_fallback_used = False

    for attempt in range(3):
        try:
            handler = await fal_client.submit_async(endpoint, arguments=arguments)
            result = await handler.get()
            video_url = result.get("video", {}).get("url")
            if not video_url:
                if attempt == 2:
                    return {"ok": False, "error": f"no video.url in response: {result}"}
                print(f"   ⚠ no video url, attempt {attempt + 1}/3")
                continue

            resp = requests.get(video_url, stream=True, timeout=180)
            resp.raise_for_status()
            output.parent.mkdir(parents=True, exist_ok=True)
            # If we have a voiceover to mix in, write Seedance MP4 to a temp path
            # first, then ffmpeg-mix into the final output.
            seedance_path = output
            if voiceover_path and Path(voiceover_path).exists():
                seedance_path = output.with_name(output.stem + "-seedance" + output.suffix)
            with open(seedance_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    f.write(chunk)

            # Mix voiceover with Seedance music+SFX using ffmpeg sidechain ducking
            if voiceover_path and Path(voiceover_path).exists():
                mix_kwargs = _mix_kwargs_from_args(args_namespace)
                print(f"→ Mixing voiceover into video with ducking + {mix_kwargs['fade_out_s']}s fade-out…")
                mix_ok = mix_voiceover_with_video(
                    seedance_path, Path(voiceover_path), output, **mix_kwargs
                )
                if not mix_ok:
                    print(f"   ⚠ ffmpeg mix failed — keeping Seedance-only audio at {output}")
                    if seedance_path != output:
                        seedance_path.replace(output)

            elapsed = time.time() - start
            size_mb = output.stat().st_size / (1024 * 1024)
            return {
                "ok": True,
                "path": str(output),
                "duration_s": total_duration,
                "size_mb": round(size_mb, 2),
                "elapsed_s": round(elapsed, 1),
                "endpoint": endpoint,
                "request_id": result.get("request_id"),
                "prompt_length_chars": len(prompt),
            }
        except Exception as e:
            msg = str(e)
            print(f"   ⚠ attempt {attempt + 1}/3 failed: {msg[:200]}")

            # Content policy violation = ByteDance moderation rejected references
            # (usually face refs). Fallback: drop everything except the storyboard
            # so the next attempt only sends @Image1. Done at most once per run.
            is_policy_block = (
                "content_policy" in msg.lower()
                or "moderation" in msg.lower()
                or "policy_violation" in msg.lower()
            )
            if is_policy_block and not content_policy_fallback_used and len(uploaded_urls) > 1:
                content_policy_fallback_used = True
                print(f"   🛟 content_policy detected — falling back to storyboard-only refs")
                if mode == "reference-to-video":
                    arguments["image_urls"] = uploaded_urls[:1]
                elif mode == "image-to-video":
                    arguments["image_url"] = uploaded_urls[0]
                # Rebuild prompt for ref_count=1 so @ImageN tags don't dangle
                fallback_prompt = build_combined_prompt(
                    brief, ref_count=1,
                    has_storyboard_first=has_storyboard_first,
                    has_voiceover=has_voiceover,
                )
                arguments["prompt"] = fallback_prompt
                print(f"   ↻ retrying with 1 ref ({len(fallback_prompt)} char prompt)")
                continue

            if attempt < 2:
                backoff = 30 * (2 ** attempt)
                print(f"   ⏳ backoff {backoff}s")
                await asyncio.sleep(backoff)
            else:
                return {"ok": False, "error": msg}


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--brief", required=True)
    parser.add_argument("--output", required=True, help="Output MP4 path")
    parser.add_argument(
        "--mode",
        choices=["reference-to-video", "image-to-video"],
        default="reference-to-video",
        help="reference-to-video: ref as style/identity anchor (default). image-to-video: ref as starting frame.",
    )
    parser.add_argument("--tier", choices=["standard", "fast"], default="standard")
    parser.add_argument("--resolution", choices=["480p", "720p", "1080p"], default="720p", help="Output resolution (default 720p — production. Use 480p for cheap tests.)")
    parser.add_argument("--reference", action="append", help="Override reference image path (repeatable, max 4)")
    parser.add_argument("--keyframes-dir", help="Directory with cut-NN-keyframe.png files to use as primary references (each one anchors one shot)")
    parser.add_argument("--max-refs", type=int, default=6, help="Max references to send (default: 6 — 1 storyboard + up to 5 product photos)")
    parser.add_argument("--no-storyboard", dest="include_storyboard", action="store_false", default=True, help="Skip the master storyboard PNG reference (default: include)")
    parser.add_argument("--voiceover", help="Path to a pre-rendered voiceover MP3/WAV. Mixed onto Seedance video in post via ffmpeg with sidechain ducking + fade-out.")
    parser.add_argument("--mix-only", action="store_true", help="Skip FAL/Seedance generation; only run ffmpeg mix (VO + music + fade-out) on the existing <output>-seedance.mp4 file. Saves cost and time when iterating on post-production.")
    parser.add_argument("--fade-out", type=float, default=1.5, help="Fade-out duration in seconds at the end of the clip (default: 1.5).")
    parser.add_argument("--dry-run", action="store_true", help="Build prompt + upload refs but skip Seedance submit. For inspecting the prompt without spending FAL credits.")
    # Sidechain ducking + mix params (defaults match references/post-mix-recipes.md).
    # Override these to tune the post-mix without editing the script.
    parser.add_argument("--vo-volume", type=float, default=2.5, help="VO track gain before mix (default 2.5).")
    parser.add_argument("--bg-volume", type=float, default=0.8, help="Seedance music+SFX gain before sidechain (default 0.8).")
    parser.add_argument("--ducking-threshold", type=float, default=0.05, help="Sidechain threshold — VO above this level activates ducking (default 0.05).")
    parser.add_argument("--ducking-ratio", type=float, default=8.0, help="Sidechain compression ratio (default 8.0). Lower = softer ducking.")
    parser.add_argument("--ducking-attack", type=int, default=20, help="Sidechain attack ms (default 20).")
    parser.add_argument("--ducking-release", type=int, default=300, help="Sidechain release ms (default 300). Longer = music doesn't blink between words.")
    parser.add_argument("--vo-mix-weight", type=float, default=1.6, help="VO weight in final amix vs ducked music=1.0 (default 1.6).")
    parser.add_argument("--yes", action="store_true", help="Skip cost confirmation")
    args = parser.parse_args()

    brief = json.load(open(args.brief))
    brief_path = Path(args.brief)
    output = Path(args.output)
    ref_overrides = [Path(r) for r in (args.reference or [])] if args.reference else None

    # MIX-ONLY mode — skip FAL generation, just remix VO + add fade-out on
    # an already-generated Seedance video. Looks for <output>-seedance.mp4
    # (created on the last full run). Falls back to <output> itself if missing.
    if args.mix_only:
        seedance_path = output.with_name(output.stem + "-seedance" + output.suffix)
        if not seedance_path.exists():
            # Fallback: maybe user kept the file as the main output (older runs
            # didn't create the -seedance backup). Snapshot it as -seedance so
            # subsequent mix-only iterations don't restack VO+fade on top of an
            # already-mixed file.
            if output.exists():
                import shutil
                print(f"⚠ {seedance_path.name} not found — snapshotting current {output.name} as the base.")
                shutil.copy2(output, seedance_path)
                print(f"   ✓ Backup created: {seedance_path.name}")
            else:
                print(f"❌ No Seedance video found at {seedance_path} or {output}")
                print(f"   Run the script without --mix-only first to generate the base video.")
                sys.exit(1)
        if not args.voiceover or not Path(args.voiceover).exists():
            print(f"❌ --mix-only requires --voiceover with an existing audio file.")
            sys.exit(1)
        print(f"🎚  Mix-only mode — skipping FAL.")
        print(f"   Seedance source: {seedance_path}")
        print(f"   Voiceover:       {args.voiceover}")
        print(f"   Fade-out:        {args.fade_out}s")
        print(f"   Final output:    {output}")
        print()
        ok = mix_voiceover_with_video(
            seedance_path, Path(args.voiceover), output, **_mix_kwargs_from_args(args)
        )
        if ok:
            size_mb = output.stat().st_size / (1024 * 1024)
            print(f"✅ Remixed → {output} ({size_mb:.1f} MB)")
            sys.exit(0)
        else:
            print(f"❌ ffmpeg mix failed.")
            sys.exit(2)

    total_sec = sum(int(c["duration"]) for c in brief.get("cuts", []))
    total_sec = min(total_sec, 15)
    price = 0.3024 if args.tier == "standard" else 0.2419
    cost = total_sec * price

    print(f"📋 Brief: {brief['campaign_slug']}")
    print(f"💰 Cost estimate: ${cost:.2f} ({total_sec}s, tier {args.tier})")
    if args.dry_run:
        print(f"🟡 --dry-run set — no FAL submit, no charge.")
    print()

    if not args.yes and not args.dry_run and cost > 1:
        ans = input("Pokračovat? [y/N] ").strip().lower()
        if ans != "y":
            print("Aborted.")
            sys.exit(0)

    result = await generate(brief, brief_path, output, args.mode, args.tier, ref_overrides, args_namespace=args)
    print()
    if not result.get("ok"):
        print(f"❌ {result.get('error')}")
        sys.exit(2)
    if result.get("dry_run"):
        print(f"✅ Dry run complete — prompt + uploads OK")
        print(f"   prompt: {result['prompt_length_chars']} chars / {result['prompt_word_count']} words")
        print(f"   refs uploaded: {len(result['uploaded_urls'])}")
        return
    print(f"✅ Done")
    print(f"   {result['path']} ({result['size_mb']} MB, {result['duration_s']}s, {result['elapsed_s']}s elapsed)")
    print(f"   request_id: {result.get('request_id')}")

    log = Path(args.brief).parent / "_singleshot-log.json"
    log.write_text(json.dumps({"args": vars(args), "result": result}, indent=2, ensure_ascii=False))
    print(f"   log: {log}")


if __name__ == "__main__":
    asyncio.run(main())
